release:
  disable: false
  github:
builds:
    - env:
        - CGO_ENABLED=0
      goarch:
       - amd64
      goos:
       - windows
       - linux
       - darwin

nfpms:
    -
      name_template: "{{ .ProjectName }}"
      replacements:
        amd64: 64-bit
        386: 32-bit
        darwin: macOS

      license: Apache 2.0
      formats:
        - deb
        - rpm

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
