#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Gobin is a tool for installing Go packages containing binaries."
    echo
    echo "Binaries are installed to the directory specified by GOBIN."
    echo "Works with all versions of Go 1.3+ and supports module versions"
    echo "with versions of Go 1.11+."
    echo
    echo "Usage:"
    echo
    echo "    $0 <package[@version]>"
    echo
    echo "Examples:"
    echo
    echo "    $0 4d63.com/tldr"
    echo "    $0 4d63.com/tldr@v1.0.0"
    echo "    GOBIN="'$HOME'"/bin $0 4d63.com/tldr@v1.0.0"
    echo
    echo "GOBIN is currently set to $(go env GOBIN)."
    exit 1
fi

package="$1"

echo "$0: GOBIN is set to $(go env GOBIN)"
echo "$0: installing $package"

pushd $(mktemp -d) > /dev/null

export GO111MODULE=on

go mod init temp 1>/dev/null 2>&1
go get -u "$package"

popd > /dev/null
