name: Publish Docker
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          OVFTOOL_LOCATION: ${{secrets.OVFTOOL_LOCATION}}
          KONFIGADM_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          name: flanksource/konfigadm
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
          snapshot: true
          buildargs: OVFTOOL_LOCATION, KONFIGADM_VERSION
