name: Test
on:
  pull_request:
jobs:
  e2e:
    runs-on: ubuntu-20.04
    container:
      image: flanksource/build-tools
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu18
          - ubuntu20
          - debian9
          - debian10
          - centos7
          - fedora29
          - amazonLinux2
          - photon3
    steps:
      - uses: actions/checkout@main
      - run: make test linux "$distro"
